from enum import Enum

class InterviewSections(Enum):
    CODING_INTERVIEW_INTRO = 1
    CODING_INTERVIEW_QUESTION_INTRO = 2
    CODING_INTERVIEW = 3
    CODING_INTERVIEW_CONCLUSION = 4
    CODING_INTERVIEW_OUTRO = 5
    CODING_INTERVIEW_FEEDBACK = 6