from enum import Enum

class InterviewTypes(Enum):
    CODING_INTERVIEW = 1
    SYSTEM_DESIGN_INTERVIEW_QUESTION_INTRO = 2
    TECHNICAL_KNOWLEDGE_INTERVIEW = 3
    DEBUGGING_INTERVIEW = 4
    BEHAVIOURAL_INTERVIEW = 5
    ML_SYSTEM_DESIGN_INTERVIEW = 6
    FRONT_END_ENGINEER_INTERVIEW = 7